server:
  port: 3355
config:
  info: "maste branch,springcloud-config/config-dev.yml version=1"


spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lonely0419/springcloud-config.git  #github上面的git仓库名字
        ###搜索目录
          search-paths:
            - springcloud-config
          #username: 1067449721@qq.com
          #password: dongxuehai123
      ###读取分支
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
